ALL_GEX_TEXT = (
    "Note to self: Don't drink tap water at Jerry Garcia's.",
    "Note to self: Don't step on any brown mushy rocks!",
    "Note to self: Don't buy rocket sled made by ACME.",
    "Will Cheech and/or Chong, report to the front desk!",
    "Hey! I feel like I'm trapped in Boy George's pants!",
    "And remember kids, never buy a marvolay from a guy with a top hat.",
    "This is like a luau at Mel Blanc's house!",
    "Ahh to see the world as Keith Richards does...",
    "Brought to you by up-Chuck Jones.",
    "What are you, Larry King's barber? Ha! Ha! You're alright!",
    "Carrot Top, is that you?"
    "Reminds me of Halloween at Rip Taylor's.",
    "This place is bigger than Drew Carey's bar tab.",
    "Man, Hef has let his place go.",
    "Don't take career advice from Joe Piscopo.",
    "This is what Tim Burton thinks about when he's in the tub.",
    "The real estate wizardry of Tom Vu at work.",
    "You have the swan-like grace of a young Nixon.",
    "Ladies and gentlemen, Tom Arnold's acting coach.",
    "How did I get in Bill Gates' head?",
    "This is like an all-nighter at Richard Simmons' house.",
    "All this technology so fat guys can hear Rush Limbaugh?",
    "All this technology and Shatner still can't get a good hairpiece.",
    "In a land before time, when Saturday Night Live was funny...",
    "I'll take 'Places I Can Burn To Death' for $100, Alex.",
    "The difference between this and Hades is that there's no Kathy Lee Gifford.",
    "And this is just one of the forty thousand rooms in Aaron Spelling's house!",
    "I haven't seen blasts like this since taco night at James Earl Jones' house."
    "I'm lost in Dick Dale's colon.",
    "Hmm, reminds me of Jackie Chan's bathroom.",
    "Captain, they are a bizarre alien race that find Adam Sandler funny.",
    "Has anyone seen Fox Mulder's sister?",
    "Scotty, beam me into an Ivy League Sorority House.",
    "Welcome to the only thing more evil than IRS Headquarters.",
)
